# Run config for reducing the flagship catalog

resume: False

pipelines: reduce_flagship_catalog

output_dir: results/reduce_flagship_catalog/outputs
log_dir: results/reduce_flagship_catalog/logs

inputs: {}

pre_script: ""
post_script: ""
